### ISSUE TITLE
feat: automatically replace fetch polyfills (isomorphic-fetch, node-fetch, unidici etc) with shims

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#1011]
A common pattern in the node ecosystem is to use polyfills for fetch. These polyfills are usually built on top of http/https built ins. Trying to use these on Workers fails because we don't have these built ins. Trying to use node_compat doesn't currently solve this problem, because the polyfills we use for http are built on XMLHTTPRequest, which isn't even available on Workers. All this rigmarole for an api that's natively available on Workers. 

While we should separately build better polyfills, my suggestion here is to automatically replace said fetch polyfills with shims to the native api. There may be slight behaviour quirks, but that's a lot better than the current situation where they don't even work.

**Comment by threepointone** [comment]
This wouldn't work for custom builds, so we could also have documentation (and maybe plugins for webpack esbuild etc) that lets folks apply it themselves.

**Comment by penalosa** [comment]
@jasnell How much will this problem be alleviated in the long run by node compat? Will it include implementations of the http module etc...?

**Comment by penalosa** [comment]
I’m going to close this issue for now, since this is a limitation of the `node_compat` system. Going forward, the Workers runtime is working on adding support for more Node.JS builtins, including possibly the `node:http` module. 

In the meantime, the best solution for now is to include your own polyfills of Node.JS builtins like `http`.
