### ISSUE TITLE
Dockerize wrangler

### ISSUE THREAD

**Issue by mrpatrick** [cloudflare/workers-sdk#1316]
### Suggestion
* It would be great to have a dockerized version of this program that is self-contained
* include an option to for build-required files (i.e. cache the template requirements in the image so they don't have to be downloaded everytime you call `build`
* include node version option

**Comment by petebacondarwin** [comment]
Transferred from Wrangler 1 repo. I think there appears to still be interest in having a Docker image, even for Wrangler 2.
Notably @michaellwest's demo at https://github.com/michaellwest/docker-wrangler-node shows that it can be achieved relatively easily.
That being said, perhaps it would be enough for us to provide good CI setup examples (maybe prepackages GitHub Actions and CircleCI Orbs) instead?

**Comment by barosl** [comment]
Yeah, I still want this, having been following this issue for years. As you said, it should be relatively easy to create a `Dockerfile` for this. Here's what I'm using personally:

```Dockerfile
FROM node
RUN npm install -g wrangler
ENTRYPOINT ["wrangler"]
```

Nothing remarkable, really. The sole reason why I want this is not due to the difficulty, but I want some authoritative sources of the Docker images I use.

**Comment by RamIdeas** [comment]
We don't currently have plans to create an official Docker image for wrangler. @barosl's suggestion above seems to cover the bases. Closing for now.

**Comment by FreeSoftwareServers** [comment]
What a bunch of corporate speak and wasted time... Like seriously the first response was such corporate copy pasta. 

It's beneficial for the same reason everyone uses Docker, it's a container and isolated. All we want is an authoritative source. I'm pretty sure somebody could make this in one day. We just want it to come straight from the authority. Seriously you could set up a continuous build deployment to a container and if you collected statistics I bet you would see extremely high utilization.... 

Being on the roadmap since 2019 and closed in 2023... Embarrassing tbh.
