### ISSUE TITLE
🐛 BUG: Usage of "typeof module" causes error "The uploaded script has no registered event handlers. [code: 10068]"

### ISSUE THREAD

**Issue by paul-go** [cloudflare/workers-sdk#1668]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Mac

### Describe the Bug

Attempting to deploy the following code causes the error:
"The uploaded script has no registered event handlers. [code: 10068]"

```
"use strict";
addEventListener("fetch", () => { });
typeof module;
```

Commenting out the last line causes the deployment to function as expected:

```
"use strict";
addEventListener("fetch", () => { });
//typeof module;
```

EDIT: Seems the same thing is happening if I change the variable after `typeof` to `exports`. Is this thing specifically trying to prevent me from detecting Node.js vs Cloudflare?

**Comment by kimyvgy** [comment]
I got the same issue after integrated `@apollo/client` into my project.

**Comment by cameron-robey** [comment]
This is due to the way we handle the two types of worker formats.
Currently we "guess" which type of worker we have - and if we find exports we assume it is a modules worker.

From `packages/wrangler/src/entry.ts` line 133:
```js
/**
 * A function to "guess" the type of worker.
 * We do this by running a lightweight build of the actual script,
 * and looking at the metafile generated by esbuild. If it has a default
 * export (or really, any exports), that means it's a "modules" worker.
 * Else, it's a "service-worker" worker. This seems hacky, but works remarkably
 * well in practice.
 */
```

For now you can bypass this "guessing" by using the command line flag `--no-bundle`.

Will discuss with the team about a potentially "better" way of detecting the type of worker to handle situations like this.

**Comment by 0x15f** [comment]
Is there any update on this issue? Encountering it using `toucan-js` and `@cfworker/sentry`, using the `--no-bundle` flag does not seem to make a difference.

**Comment by jfsiii** [comment]
I'm also seeing this failure, but only in `NODE_ENV=development` builds of our [`remix`](https://remix.run/) project. `wrangler dev` works fine but `NODE_ENV=development wrangler dev` fails.

We're using the `[build.command]` in `wrangler.toml` to run `remix build` which creates a single `build/index.js` entrypoint. 

It's a bit hard to debug where the issue's coming from but I do see a `typeof module` in the failing dev builds that's not in the passing builds

```
> ack 'typeof module' path/to/build/index.js
      typeof exports == "object" && typeof module < "u" ? r2(exports) : typeof define == "function" && define.amd ? define(["exports"], r2) : (e2 = e2 || self, r2(e2.stylis = {}));
```

We first ran into this a few months ago while upgrading from remix `1.6.8` to remix `1.7.2`. We could reliably trigger the issue by switching those versions, but couldn't figure out the source of the issue.

Since remix can _only_ run the `service-worker` format at the moment https://github.com/cloudflare/wrangler2/issues/1668, and because we need to create dev builds (e.g. for profiling), we used this patch to bypass the issue until it's resolved

```patch
diff --git a/node_modules/wrangler/wrangler-dist/cli.js b/node_modules/wrangler/wrangler-dist/cli.js
index c999f82..a596b06 100644
--- a/node_modules/wrangler/wrangler-dist/cli.js
+++ b/node_modules/wrangler/wrangler-dist/cli.js
@@ -141778,7 +141778,7 @@ async function guessWorkerFormat(entryFile, entryWorkingDirectory, hint, tsconfi
   const scriptExports = entryPoints[0][1].exports;
   if (scriptExports.length > 0) {
     if (scriptExports.includes("default")) {
-      guessedWorkerFormat = "modules";
+      guessedWorkerFormat = "service-worker"; console.log("patch to force 'service-worker' format"); /* Remix can *only* ship service-workers on Cloudflare https://github.com/cloudflare/wrangler2/issues/1668 & https://github.com/remix-run/remix/issues/764 */
     } else {
       logger.warn(
         `The entrypoint ${import_node_path10.default.relative(
```

**Comment by jfsiii** [comment]
Following up to say we updated to `2.11` and everything works as expected without any patching.
