### ISSUE TITLE
🐛 BUG: Many routes in wrangler.toml causes publish to be extremely slow

### ISSUE THREAD

**Issue by jahands** [cloudflare/workers-sdk#2242]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

WSL (Ubuntu 22.04)

### Describe the Bug

I have a Worker Service containing 27 routes, that I've historically managed the routes for via Dash. I decided to try managing these via wrangler.toml, but I ran into an issue: it makes publish 15x slower.

After adding the routes, this Publish step went from 0 to 20 seconds:
`npx wrangler publish`
![image](https://user-images.githubusercontent.com/10719325/202912817-f86bfee2-5e9b-4312-8968-5673760888be.png)

To repro, add 27+ routes to a project and publish it with wrangler.

Maybe we could add some concurrency to the Routes API calls?

**Comment by JacobMGEvans** [comment]
Greetings! 
Is this still an issue you are running into?

**Comment by penalosa** [comment]
We're closing this for now, since we haven't heard from you in a while—if it's still an issue feel free to add more details and we can investigate. In particular, details like whether these are custom domains or regular routes would be helpful, and whether they involve multiple zones. From a quick glance, it seems like the routes are uploaded using a single API call, rather than parallel ones, and so there isn't much opportunity for concurrency.
