### ISSUE TITLE
🐛 BUG: D1 TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Bulbang** [cloudflare/workers-sdk#2456]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Mac

### Describe the Bug

`db.prepare(query).first()`

Throws `TypeError: Cannot read properties of undefined (reading 'length')`

Variables used in code example:

`this.database: D1Database`
```
newArticle = {
	"title": "Hello World It's Me",
	"meta_title": "we need to create that record",
	"meta_description": "to go production",
	"file_id": "fea4ef30-da7f-4d35-8c9d-cb7d68943311",
	"slug": "hello-world-its-me",
	"blocks": "{\"props\":{\"blockMap\":{\"time\":1672070736942,\"blocks\":[{\"id\":\"A2kGtZQEMp\",\"type\":\"paragraph\",\"data\":{\"text\":\"Some Text<br>\"}}],\"version\":\"2.24.3\"}}}",
	"hidden": 0,
	"created_at": 1672070738032,
	"updated_at": 1672070738032
}
```
Code example:
```
try {
    console.log(2);
    const result = await this.database
        .prepare(
            `INSERT INTO articles(${Object.keys(newArticle).join(
                ',',
            )}) VALUES (${Object.values(newArticle)
                .map((val) => `'${val}'`)
                .join(',')}) RETURNING *`,
        )
        .first<Article>()
        console.log(1);
        
    result.blocks = JSON.parse(result.blocks)
    return result
} catch (error) {
    console.log(error)
    throw new Error('D1 insert operation error')
}
```

Worker Logs:

```
"logs": [
    {
      "message": [
        2
      ],
      "level": "log",
      "timestamp": 1672068766683
    },
    {
      "message": [
        "TypeError: Cannot read properties of undefined (reading 'length')"
      ],
      "level": "log",
      "timestamp": 1672068766921
    }
  ],
```

**Comment by penalosa** [comment]
Hi @Bulbang! Thanks for flagging this. In an effort to remove stale issues so we can have better signal on current friction points, we’re closing out issues that have not been updated within the last 6 months. If this is still a problem, please feel free to open a new issue referencing this one. Please be sure to include an updated summary and any additional context and we will review. D1 has seen active development since it's alpha (recently going open beta: https://blog.cloudflare.com/d1-open-beta-is-here/), and so it's likely that your issue has been resolved in the meantime. Thank you!
