### ISSUE TITLE
🚀 Feature Request: Universal color support

### ISSUE THREAD

**Issue by demosjarco** [cloudflare/workers-sdk#2693]
### Describe the solution

Wrangler logs from `dev` and `tail` seem to support color (using [`colors`](https://www.npmjs.com/package/colors)), but workers web ui's tail does not.

![image](https://user-images.githubusercontent.com/1209494/217654978-a517ae92-0a4f-4481-b893-7e88d1d3db17.png)

**Comment by penalosa** [comment]
Thanks for raising this! This is because Wrangler renders the contents of your log messages, whereas the dashboard renders the entire JSON payload coming from the workers runtime. We're unlikely to support ANSI colour codes in the dashboard for logs in the near future, and so I'm going to close this for now.
