### ISSUE TITLE
🐛 BUG: `wrangler generate` sometimes fails due to cross-device renaming

### ISSUE THREAD

**Issue by penalosa** [cloudflare/workers-sdk#2850]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2

### What operating system are you using?

Windows

### Describe the Bug

Run `wrangler generate` with any template. It will fail.

The solution is to switch from `fs.renameSync` to a `copy` and `unlink` approach in `git-client.ts`

**Comment by Cherry** [comment]
This issue is still prevalent in wrangler 3. It's very common in Windows for folks to install their Operating System on one drive, but have user files on another. In my case, I have my OS on `C:/` and my user files on `E:/` and running `npx wrangler@latest generate project-name https://github.com/cloudflare/workers-sdk/templates/experimental/worker-rust` there for example results in:

```
 ⛅️ wrangler 3.0.1
------------------
▲ [WARNING] The `generate` command is no longer supported and will be removed in a future version.


Creating a worker in project-name from https://github.com/cloudflare/workers-sdk/templates/experimental/worker-rust

✘ [ERROR] Failed to find "templates/experimental/worker-rust" in https://github.com/cloudflare/workers-sdk.git
```

**Comment by Cherry** [comment]
I’ve got a PR up to fix this at https://github.com/cloudflare/workers-sdk/pull/3403.

I don’t know how best to test this behaviour with wrangler’s tests, but with manual testing it works well. I’m happy to explore adding tests if someone can provide some guidance, but it would be really good to land this.
