### ISSUE TITLE
🚀 Feature Request: Regular `esbuild` updates

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#2980]
`wrangler` is currently pinned to `esbuild` version `0.16.3`. While this makes a lot of sense for stability, it limits a lot of functionality with newer TypeScript (and even some JavaScript) features that pushes people to use Custom Builds.

I would love to see this bumped with every wrangler release (maybe only minor, not patch?), assuming there's enough tests to validate things work well. The biggest changes appear to be in `0.17.0` with the build API.

esbuild changelog since `0.16.3`: https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#01614

**Comment by PabloSzx** [comment]
Can this get a little bit of priority?

esbuild 0.16.3 was released Dec 8, 2022

We are at August 1st 2023, and esbuild is version 0.18.17


@lrapoport-cf @penalosa @mrbbot

**Comment by lrapoport-cf** [comment]
hi @Cherry and @PabloSzx , thanks for raising this :) this has been prioritized and is now assigned 👍

**Comment by Cherry** [comment]
#3772 will update the esbuild version which is awesome to see! Is there a plan to keep this regularly updated so this issue doesn't get created again in 1, 3, 6, 12, etc. months?

**Comment by jspspike** [comment]
@Cherry The team is still discussing but the tentative plan for future updates is to update patch changes as they happen and update to the latest version on every major version bump of wrangler

**Comment by jspspike** [comment]
Update on this issue. #3772 will bump esbuild to 0.17.19. 0.18 has breaking changes so we will bump esbuild to 0.18.20 on the next major version release of wrangler.

In order to bump to 0.19 we need [this issue](https://github.com/evanw/esbuild/issues/3337) to be resolved but once that is done we can get on a regular cadence of bumping the esbuild version as described in my last comment.
