### ISSUE TITLE
🚀 Feature Request: Durable objects with CF Pages in advanced mode

### ISSUE THREAD

**Issue by caracal7** [cloudflare/workers-sdk#3050]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

Mac

### Describe the Bug

DO work fine locally, but are not created in the cloud when I deploy a project folder with `wrangler pages publish public`.
With `wrangler pages dev public --live-reload"` Durable objects is working as expected.
All Durable objects class are exported in `_worker.js`.
I used this template as starter https://developers.cloudflare.com/pages/framework-guides/deploy-a-hono-site/

Of course I can deploy DO as separate Worker but it would be convenient to do everything in one place

**Comment by penalosa** [comment]
Thanks for reporting this! Would you be able to make a reproduction repository and link it?

**Comment by caracal7** [comment]
> Thanks for reporting this! Would you be able to make a reproduction repository and link it?

No problem 🙃

https://github.com/caracal7/cloudflare-durable-objects-pages

**Comment by vassbence** [comment]
I have just ran into this too, would love to see it resolved.

**Comment by mnishihan** [comment]
Any update on this?? I'm also running into this issue with a remix app, configured to build in worker mode.

**Comment by CarmenPopoviciu** [comment]
hi folks 🌟 

We recently added [`wrangler.toml` support](https://developers.cloudflare.com/pages/functions/wrangler-configuration/) for Pages, which should make [integration of DOs with Pages](https://developers.cloudflare.com/pages/functions/wrangler-configuration/#durable-objects) a little bit easier, regardless of the Pages project being a Functions or Advanced Mode one.

Also, please be aware that Pages itself does not create and deploy Durable Objects within a Pages project. Currently this is the expected behaviour. You must create a Durable Object Worker and bind it to your Pages project using the Cloudflare dashboard or your Pages project’s `wrangler.toml`:

```
# wrangler.toml

[[durable_objects.bindings]]
name = "MY_DO"
class_name = "DurableObjectClass"
script_name = "WorkerScriptName"
```

I am not aware of any plans, at least on the short term, to change this current behaviour I'm afraid. We will however discuss your feedback internally, as we are aware that the Pages + DO story is not optimal at the moment, and we understand the friction our users have to go through <3

Leaving this open for now, until we have discussed internally
