### ISSUE TITLE
🐛 BUG: Proxying `wrangler pages dev` with `<command>` not working on Windows

### ISSUE THREAD

**Issue by stenet** [cloudflare/workers-sdk#3054]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.15.0

### What operating system are you using?

Windows

### Describe the Bug

I have a simple Nuxt app and want to proxy the traffic through wrangler to use _worker.js (on Windows).

When executing `npx wrangler pages dev -- nuxt dev` the result is:

![image](https://user-images.githubusercontent.com/1838511/232487710-c6b74133-9a3f-4306-b1ff-c07a3cf27020.png)

I also tried using `npx wrangler pages dev --proxy 3000 -- nuxt dev`. That didn't work either.

This is the link to the repo: https://github.com/stenet/nuxt-cf-pages. You can use `npm run dev` to execute the above statement.

When cloning this repo an a Mac or Linux everything works as excepted.

**Comment by CarmenPopoviciu** [comment]
thank you for reporting this and thank you SO  much for the repro repository. We'll have a look at it and come back to you once we've figured it out

**Comment by Sammy-T** [comment]
@stenet What error do you receive when you specify the port?
I'm just wondering if this is related to #2244

**Comment by CarmenPopoviciu** [comment]
hi @stenet 👋 
my most sincere apologies for taking literally one year 😭 to get back to you on this </3. Will go in a corner and cry once I finish typing this reply 😅 

Lots have changed since you first reported this issue, and unfortunately, one of those is things is that Pages support for the proxy command has been deprecated, and we no longer recommend folks to use it.

For now, the recommended way is to build your application to a directory and run the `wrangler pages dev <directory>` command instead. This will result in a more faithful emulation of production behavior than via `<command>`.

We are aware this is not most ideal, especially for HMR. We will be discussing this internally as part of https://github.com/cloudflare/workers-sdk/milestone/10, but what comes out of those discussions remains to be seen.

For now, closing as won't fix due to API being deprecated

<3
