### ISSUE TITLE
🐛 BUG: C3 next.2 still deploys Qwik apps to the preview environment

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workers-sdk#3220]
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

c3@2.0.0-next.2

### What operating system are you using?

Mac

### Describe the Bug

This is a QwikCity bug but wanted to capture it here for posterity.

```
npm create cloudflare@next -- --type webFramework --framework qwik
```

fails to deploy properly because the QwikCity scaffolds the project with incorrect deploy command in `package.json`:

```
  "scripts": {
    ...
    "deploy": "wrangler pages publish ./dist --branch preview",
    ...
  }
```

the branch specifier above should be `production` and not `preview`.

This means that all deployments are available at `preview.<project-name>.pages.dev` instead of `<project-name>.pages.dev`.

**Comment by IgorMinar** [comment]
@manucorporat @adamdbradley @mhevery can you please help?

**Comment by travisby** [comment]
Just tacking on here -- I've noticed the same (for a different reason) with deploying an Astro app.

Both when astro creates a git repo, as well as when I tell astro to not create a git repo (and tell cloudflare to create it), the branch is `master` (I assume due to my local env), and then the page deployment uses `master`, which becomes a preview deploy.  

The package.json doesn't specifically specify the `preview` branch like this issue, however.
