### ISSUE TITLE
🐛 BUG: Exit with 137 when OOM

### ISSUE THREAD

**Issue by jeroenvdheuvel** [cloudflare/workers-sdk#3226]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.20.0

### What operating system are you using?

Linux

### Describe the Bug

Out-of-memory kill is not being reported and npx marks the page deployment as a success while the process ran out of memory.

Out-of-memory output:
<img width="1007" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/5213151/186a15be-6460-4e73-899e-7b354b0cb3bc">
The GItlab job is marked as a success because the npx process has an exit code 0.

Successful output (with more memory)
<img width="1116" alt="image" src="https://github.com/cloudflare/workers-sdk/assets/5213151/5440ecea-a501-4cd8-b49b-30d2db30616c">

It would be great when the exit code reflects what happened. In the case of not having enough memory an exit code 137 would make sense. Anything except 0 would be fine too.

**Comment by sidharthachatterjee** [comment]
It appears that this is an issue with npm cli (which npx is a part of) and not us since when we are out of memory, wrangler is terminated and the exit code is sent back via npx. 

In that vein, we will be closing this issue and I'd encourage you to open one in https://github.com/npm/cli

Cheers and have a nice day!
