### ISSUE TITLE
🐛 BUG: Wrangler cannot build on Mac devices

### ISSUE THREAD

**Issue by DeJayDev** [cloudflare/workers-sdk#3321]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.0.1

### What operating system are you using?

Mac

### Describe the Bug

It is impossible to install Wrangler through `npm` on MacOS. Observe by running `npm i -g wrangler`.

[Please review the following log](https://pastebin.com/id3XLtm0)... it appears to be triggered by a dependency, `better-sqlite3` which claims to have prebuilt binaries for Node LTS versions but as we can see here that's not correct.

Mac OS Version:
```
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

Node Versions:
```
Node v18.16.0
node-gyp v9.3.1
npm 9.6.6
```

Edit: Similarly to the others, I am running an Apple M1 Pro Mac.

**Comment by Abbe98** [comment]
I have the same issue and error on Fedora Linux.

**Comment by adv1996** [comment]
Also running into the same issue on Mac M1

**Comment by pbelbin** [comment]
I have seen this issue too.  I was using Yarn, but had a similar result.  It would not install.

The crux of the issue seems to be that installing Wrangler into a project that has a bunch of conflicting other dependencies seems to trip up the Wrangler install.

I've been working on something that involves having a template of a Wrangler project that gets re-used by CLI tooling that uses the template to generate a Wrangler project.

What I found was that by adding the Wrangler CLI to the tooling-generated Wrangler project itself as a local dev dependency worked OK.

ie:
- within the Wrangler worker folder (that has a package.json file), `touch yarn.lock`(this ensures Yarn sees this as a thing that's a stand-alone thing rather than part of a larger package)
- ensure the Wrangler project has a dev dependency on the Wrangler command.  In my case, it was version 3.0.1
- do `yarn install`

The result of the above seems to produce a successful Wrangler install that's private to the Wrangler project!

From what I can see, the above somehow keeps things isolated enough that Wrangler CLI can be installed cleanly.

This was done on a system running macOS 13.4 with M / arm64 CPU.

**Comment by JacobMGEvans** [comment]
> Please review the following log

Great response! Thank you for helping out @pbelbin 

@DeJayDev if this does not solve your issue and you have tried removing `node_modules` and reinstalling or `npm rebuild` with no success please feel free to reopen the issue.
