### ISSUE TITLE
🐛 BUG: unstable_dev can't be used with local: false since v3

### ISSUE THREAD

**Issue by vvo** [cloudflare/workers-sdk#3526]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.1

### What operating system are you using?

Mac

### Describe the Bug

Before v3 we were doing this:

```ts
const worker = await unstable_dev('src/blob-storage-worker-source.ts', {
  local: false
});
```

And it would publish the worker in a preview worker. This is no more working with v3 as it seems to be relying only on args sent via the command line like --remote. Which can't be set via `unstable_dev`. I believe `unstable_dev` wasn't part of the v3 upgrade perhaps?

We're using this technique in our tests.

**Comment by jeansibelius** [comment]
+1

Noticed this same issue, when trying to set up tests with wrangler 3 and as a workaround seeding data to preview instances with the wrangler cli.

**Comment by eugene1g** [comment]
I think if you pass `remote: true` instead of `local: false`, it will run in an actual remote worker. TypeScript doesn't like that property, but the value is passed down https://github.com/cloudflare/workers-sdk/blob/cb26366cb63427136fec4fdf6ec2da8fb411da29/packages/wrangler/src/dev.tsx#L444C1-L445C1
