### ISSUE TITLE
🐛 BUG: Unable to write to R2 locally

### ISSUE THREAD

**Issue by mrturck** [cloudflare/workers-sdk#3679]
### Which Cloudflare product(s) does this pertain to?

R2, Wrangler core

### What version(s) of the tool(s) are you using?

3.1.1

### What version of Node are you using?

18.16.1

### What operating system are you using?

Mac

### Describe the Bug

I am writing a small text object to R2 during local development, I am using fetch syntax for my worker:
`await R2_BUCKET.put(<name of file>.txt, JSON.stringify(result))`

I log the output of the Put operation and get what appears to be a successful result:
`{"customMetadata":{},"httpMetadata":{},"uploaded":"2023-07-26T23:47:39.528Z","checksums":{"md5":"9eaa7...5d37"},"httpEtag":"\"9ea5337ab....2560d537\"","etag":"9ad3....7ab256bed7","size":260,"version":"646....8f5f5dc2d1","key": <name of file>}
`

My binding looks like this in my wrangler.toml:
```
[[r2_buckets]]
  bucket_name = <name of bucket>
  preview_bucket_name = <name of bucket>
  binding = "R2_BUCKET"
```

When I go to the bucket the file does not exist. This problem only seems to happen locally. Once deployed, things work as expected.

I have confirmed my bindings and can see that they are correct during dev startup.

**Comment by penalosa** [comment]
Thanks fo raising this issue! This is intentional, and is how `wrangler dev` is intended to work. 
* When you run `wrangler dev`, all R2 etc... operations run locally, and won't affect your remote resources.
* When you run `wrangler dev --remote`, all R2 etc... operations run _remotely_, and _will_ affect your remote resources.
