### ISSUE TITLE
🐛 BUG: wrangler pages dev doesn't recompile worker when imported dependency changes

### ISSUE THREAD

**Issue by mariusGundersen** [cloudflare/workers-sdk#3840]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.6.0

### What version of Node are you using?

18.13.0

### What operating system are you using?

Windows

### Describe the Bug

When running `wrangler pages dev` the worker is compiled automatically whenever a file in /functions is changed. However, if a dependency of one of those files changes it does not recompile.

For example, given
```js
// functions/test.js
import lib from '../lib/lib.js';

export async function onRequest() {
  return new Response(`<h1>${lib()}</h1>`, {
    headers: {
      'Content-Type': 'text/html'
    }
  })
}

// lib/lib.js
export default function () {
  return 'Testing';
}
```

Then when running `wrangler pages dev` any change to `functions/test.js` will cause the worker to recompile and refreshing the browser page will reflect that. If however the string in `lib/lib.js` is changed the worker is not recompiled and refreshing the page in the browser will not reflect those changes.

**Comment by CarmenPopoviciu** [comment]
hi @mariusGundersen 

Thank you so much for raising this issue and providing all the helpful details that you did <3. 

I was able to reproduce the behaviour you described, so this is indeed an issue. In fact, we have a similar report in https://github.com/cloudflare/workers-sdk/issues/4824. As I mentione there

> reloading on dependency changes actually used to work, but we seem to have introduced a regression with
> https://github.com/cloudflare/workers-sdk/pull/3311. I need to double check this, but preliminary testing would seem to indicate that. I 
> don't have enough context on those changes to know whether the regression was intentional or not, and I do not know if re-enabling 
> esbuild's watch mode for Pages would not introduce the same performance issues as those reported in 
> https://github.com/cloudflare/workers-sdk/issues/3258. Something I need to look into. But I agree with the general sentiment that this 
> is something we should support

I will be picking up these two issues as part of https://github.com/cloudflare/workers-sdk/milestone/10 and will update here once the fix for this particular report is ready.
