### ISSUE TITLE
`wrangler –assets` flag incorrect mime type for binary files

### ISSUE THREAD

**Issue by broccolihighkicks** [cloudflare/workers-sdk#4000]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.8.0

### What version of Node are you using?

v20.5.1

### What operating system are you using?

Mac

### Describe the Bug

`wrangler dev --assets ./src/static` serves binary .sqlite files as `text/plain`.

How can I get it to return `application/octet-stream`?

**Comment by petebacondarwin** [comment]
From looking through the code it appears that we rely upon the `mime` npm package to convert file extensions to mime types: https://github.com/broofa/mime. See https://github.com/cloudflare/kv-asset-handler/blob/264c0b1dd2e9124b7328961594f33cbe66dc8145/src/index.ts#L161.

From looking at that `mime` package it seems that `.sqlite` is not listed as a known extension. See https://github.com/broofa/mime/blob/main/types/standard.ts. You could try submitting an issue there.

Since kv-asset-handler was designed for Workers Sites, which has been superceded by Cloudflare Pages, I think that it is unlikely that that package will be changed to fix this.
