### ISSUE TITLE
🐛 BUG: C3 - creating an Angular project fails with pnpm

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workers-sdk#4023]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

C3 2.3.0

### What operating system are you using?

Mac

### Describe the Bug

If I try to create a new Angular project using pnpm (via `pnpm dlx create-cloudflare@latest`) the process errors out:
![Screenshot 2023-09-25 at 12 50 22](https://github.com/cloudflare/workers-sdk/assets/61631103/d95d16e2-b663-469f-964f-2b3688896865)

The issue is that this code
https://github.com/cloudflare/workers-sdk/blob/ef949392311683e5fc1ace1e5509ee77d7ab88e4/packages/create-cloudflare/src/frameworks/angular/index.ts#L32
runs `pnpm @angular/cli@next analytics disable` instead of running `pnpm dlx @angular/cli@next analytics disable`

Note: the application still gets created since this failure happens around the end of the process

**Comment by dario-piotrowicz** [comment]
This issue is related to #3654 in the sense that npx isn't currently correctly converted to the appropriate pnpm equivalent

(PS: I've been working on this small utility library: [package-manager-manager](https://www.npmjs.com/package/package-manager-manager), if we'd like to give it a shot I think it should really help here)

**Comment by jculvey** [comment]
Looks like this particular failure is because we should be running `ng` instead of `@angular/cli`. There's an installed copy of it already and we should be able to `bunx`, `npx`, or `pnpm exec` it. 

We should change `pnpm` to `pnpm exec` for v6+ however (even though it technically does work as `pnpm ng ...`). I'll tackle address that with a fix under this issue: https://github.com/cloudflare/workers-sdk/issues/3654
