### ISSUE TITLE
🚀 Feature Request: Ability to change node polyfills

### ISSUE THREAD

**Issue by promentol** [cloudflare/workers-sdk#4233]
### Describe the solution

Dear Wrangler Team

The node.js compatibility mode is using the following library
https://github.com/ionic-team/rollup-plugin-node-polyfills/

This library last time was  updated 4 years ago, it have 29 open issues, and 25 pending issues, and it's not maintained anymore. And it is missing recently added libraries of node.js.

My problem is the npm package I am trying to import is using perf_hooks package. And I can't add it's polyfill there.

Solution 1: Allow to change the git repository or package the polyfill is using.

Solution 2: esbuild alias can be also used, we need a way to configure esbuild package, without overriding the entire build command from wrangler.toml, may be we can just include custom esbuild config file which will extend the original esbuild config file from wrangler?

**Comment by penalosa** [comment]
Since this issue was opened, we've landed on a new approach for Node.js compatibility that doesn't rely on outdated polyfills. You should be able to follow the docs at https://developers.cloudflare.com/workers/runtime-apis/nodejs/, but TLDR adding the following to your `wrangler.toml` file (and removing `node_compat = true`) should be enough to try out the new Node.js compat mode:

```
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
```
