### ISSUE TITLE
🐛 BUG: pages dev output is unnecessarily verbose

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#4265]
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0

### What version of Node are you using?

18.18.0

### What operating system are you using?

Windows

### Describe the Bug

When running `npx wrangler pages dev <dir>`, you get a _LOT_ of verbose output:

![image](https://github.com/cloudflare/workers-sdk/assets/856748/6604a95b-61db-49e1-90e7-544a10530b59)

```
> npx wrangler pages dev ./dist

▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-10-23.

  Pass it in your terminal:
  \`\`\`
  --compatibility-date=2023-10-23
  \`\`\`
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


Compiling worker to "C:\Users\james\AppData\Local\Temp\functionsWorker-0.005178014829587907.mjs"...
✨ Compiled Worker successfully
 ⛅️ wrangler 3.14.0
-------------------
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


⎔ Starting local server...
▲ [WARNING] Parsed 5 valid header rules.


[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-10-16",
but you've requested "2023-10-23". Falling back to "2023-10-16"...
kj/async-io-win32.c++:982: warning: Bind address resolved to multiple addresses.  Only the first address will be used.  If this is incorrect, specify the address numerically.  This may be fixed in the future.; addrs[0].toString() = 127.0.0.1:59452
[mf:inf] Ready on http://0.0.0.0:8788
[mf:inf] - http://172.22.208.1:8788
[mf:inf] - http://192.168.50.240:8788
[mf:inf] - http://127.0.0.1:8788
```

That's a lot of visual noise to try and scan and determine if my command was successful or not.

This is without any `wrangler.toml` in my directory.

Actionable things I'd recommend:

- Reduce compat date warnings. Improved in https://github.com/cloudflare/workers-sdk/pull/4209
- Remove `--local` warning - pages dev is ONLY local and I didn't even pass this. I suspect it's coming from `unstable_dev`: https://github.com/cloudflare/workers-sdk/pull/4687
- Remove "warnings" for valid header rules
- Remove workerd startup warnings with multiple networks in windows: https://github.com/cloudflare/workerd/issues/1408

**Comment by klaemo** [comment]
I can confirm this and it's still like that in `3.15.0`

```
npx wrangler pages dev dist                                
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-11-09.

  Pass it in your terminal:
  \```
  --compatibility-date=2023-11-09
  \```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more
  information.


Compiling worker to "/Users/clemens/Projects/webapp/.wrangler/tmp/pages-10DKtg/functionsWorker-0.21075951104789326.mjs"...
✨ Compiled Worker successfully
 ⛅️ wrangler 3.15.0
-------------------
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


Using vars defined in .dev.vars
Your worker has access to the following bindings:
- Vars:
  - API_URL: "(hidden)"
⎔ Starting local server...
▲ [WARNING] Parsed 1 valid redirect rule.


▲ [WARNING] Parsed 3 valid header rules.
```

There are just way too many warnings for a successful operation

- the `compatibility-date` warning is confusing. If I'm required to pass this, why is it an optional flag?
- the warning about `--local` is just plain wrong, because I didn't pass that flag
- the warnings about **valid** header and redirect rules prompted me to check if I did something wrong...but apparently not

I think a one liner log message for the successful start of the local server would be sufficient. Something like:

```
Started local server on http://0.0.0.0:8788 with 1 redirect rule, 3 header rules and compatibility-date=2023-11-09.
```

or if you want to to be slightly more verbose:
```
Local server listing on http://0.0.0.0:8788
- detected 1 redirect rule
- detected 3 header rules
- using compatibility date "2023-11-09"
```

**Comment by newsve** [comment]
It gets worse if you use something like Vite, then you see thousands of urls on every request to the dev servers and can't catch any of our own console.logs anymore

**Comment by treeder** [comment]
I'm with @newsve , can we silence the request log messages?  I only want to see what I'm logging. Or perhaps a `--verbose` option to see every single request. This is what happens now, hundreds of request logs making it hard to find the important stuff:

![image](https://github.com/cloudflare/workers-sdk/assets/75826/ba2e60d5-4cc0-4865-9f96-ab2bf8b46c15)

**Comment by CarmenPopoviciu** [comment]
Hi folks,

First of all, thank you for raising this issue, and for providing us will the information you did <3!

As we are picking this up as part of https://github.com/cloudflare/workers-sdk/milestone/10, I just want to confirm the current state of affairs, as codebase has evolved since this issue was first reported.

Running `wrangler pages dev [directory]` in wrangler version `3.57.0`, in a [Pages project](https://github.com/cloudflare/workers-sdk/tree/main/fixtures/pages-functions-with-routes-app) with:
- Functions
- `_routes.json`
- `_headers`
- `_redirects`
- no `wrangler.toml` file

 currently outputs the following:

<img width="1133" alt="Screenshot 2024-05-17 at 12 40 00" src="https://github.com/cloudflare/workers-sdk/assets/4638332/d80bb318-62a4-4135-8b9d-71bbd52ab3da">

In the original report by @Cherry the suggested actionable items were:
- Reduce compat date warnings. [**Applicable**]
- Remove --local warning - pages dev is ONLY local and I didn't even pass this. [**N/A** as these warnings were already [removed](https://github.com/cloudflare/workers-sdk/pull/3224/files#diff-c90ff1ca6d929baaafb7d67d6d6ccd573593762adf4e7a9b6917343ceeceb68bR194-R197)]
- Remove "warnings" for valid header rules. [**N/A** as these were [converted](https://github.com/cloudflare/workers-sdk/commit/6a4cb8c6456f1dba95cae2b8bbe658f7227349f8#diff-162f907a27ba9f567910b6a488cde54dd9606048cadaeaa25d4e6e46d3738715R62) to logs instead of warnings, but please see my followup question below]
- Remove workerd startup warnings with multiple networks in windows. [**TBD?** will need to repro, but wondering if folks are still experiencing this?]

Subsequent reports also suggested to
- Silence the request log messages [**TBD** as this is not `pages` specific, but is output by both `wrangler dev` and `wrangler pages dev`]

`// "wrangler dev" output`
<img width="1128" alt="Screenshot 2024-05-17 at 12 58 13" src="https://github.com/cloudflare/workers-sdk/assets/4638332/e02d3d1e-6dd1-455c-b7bd-5e58772f4723">

In addition to what was already suggested in these discussions, I'm wondering if logs such as:

- `Compiling worker to "/.../pages-functions-with-routes-app/.wrangler/tmp/pages-IIkQRR/functionsWorker-0.6251491221119416.mjs"...`
- `Parsed 1 valid redirect rule.`
- `Parsed 1 valid header rule.`
- 
are helpful or become noise? Do you have any input on that?

**Comment by Cherry** [comment]
Personally, I think most of my original issues with the verbosity of this have since been resolved.

The compatibility date warning is a bit noisy when you don't specify one (and should maybe recommend `wrangler.toml` now instead?), but at least you don't get one now from both `pages dev`, and `miniflare`.

And then the "Compiling worker" line is a little verbose and unnecessary, but everything else is useful information now I think.

**Comment by CarmenPopoviciu** [comment]
I abs agree with you @Cherry that compat date and fns compilation output is noisy. I'll add fixes for both, plus some extra things to make the output more readable and more organised and circle back here. In the meanwhile anyone insterested in this can follow the progress over at https://github.com/cloudflare/workers-sdk/pull/5927
