### ISSUE TITLE
🐛 BUG: create-cloudflare tried to commit to my git repo without asking me

### ISSUE THREAD

**Issue by Walluce** [cloudflare/workers-sdk#4273]
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

create-cloudflare 2.6.1

### What version of Node are you using?

v18.17.1

### What operating system are you using?

Windows

### Describe the Bug

I was a little shocked to see that when I simply tried to create a new worker, create-cloudflare tried to commit to my git repo without asking me.  
I feel this should be something that is not turned on by default.

**Comment by dario-piotrowicz** [comment]
@Walluce thank so very much for the issue, this is something I had on my mind for a while, we don't have a great behaviour for when you run C3 in pre-existing repositories.

We have some various alternatives (one of which is basically this: https://github.com/cloudflare/workers-sdk/pull/4205) I was already planning to open a Github discussion in the next few days to see what people think 👍 

By the way, I would be really interested to hear about your use case if you don't mind, could you tell me why you were using C3 inside of an existing git repo? was that a monorepo?

**Comment by Walluce** [comment]
Hi Dario,

I was planning to create a monorepo, but this was my first worker. I had basically just created the repo in the Github UI, and cloned it to my PC. Then I ran the script and saw that it was trying to commit.

TBH, I am struggling to understand why the code to commit is in this script in the first place. At the very least it should be behind a flag?

Regards,
Walluce




Regards,
Walluce Pinkham


Internal - Intellectual Property

________________________________

**Comment by dario-piotrowicz** [comment]
Thanks @Walluce that's a good point, I didn't think this was problematic for fresh new git repos, but I can see your point and why you believe it to be surprising... maybe we should only commit when we do initialize the git repository 🤔

**Comment by dario-piotrowicz** [comment]
I looked a bit into this and it seems that generally most framework CLIs do commit only when they initialize the git repository, a few examples:
 - create-next-app: https://github.com/vercel/next.js/blob/27bfd2d2300f0946749ac4724e91526b0371dbe8/packages/create-next-app/helpers/git.ts#L30
 - create-qwik:
https://github.com/BuilderIO/qwik/blob/a07c3cde1ae6d8cb2c8649f4ad88c04c189afb5c/packages/create-qwik/src/run-create-interactive-cli.ts#L147
- create-remix:
https://github.com/BuilderIO/qwik/blob/a07c3cde1ae6d8cb2c8649f4ad88c04c189afb5c/packages/create-qwik/src/run-create-interactive-cli.ts#L147
- nuxt doesn't seem to do any committing at all:
https://github.com/nuxt/cli/blob/main/src/commands/init.ts

Likely what we ought to do is to commit when we initialize the repo otherwise if C3 is running inside an already existing repo, we should not commit or prompt the user for permissions to commit.

**Comment by Walluce** [comment]
Thank you, I would be happy with that behavior

Regards,
Walluce Pinkham


Internal - Intellectual Property

________________________________
