### ISSUE TITLE
🐛 BUG: Can't put script path after `--var`

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/workers-sdk#4283]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0

### What version of Node are you using?

Node.js v20.6.1

### What operating system are you using?

MacOS

### Describe the Bug

Running a command such as `wrangler deploy --no-bundle --env ${env} --var RELEASE:${release} dist/index.js` will put the script into env vars and break (if no script defined in wrangler.toml or if the script that is defined isn't valid for deployment -- this may also just break in general since the env name will be invalid)

Output:
```
 ⛅️ wrangler 3.14.0
-------------------
Your worker has access to the following bindings:
- ...
- Vars:
  - ENVIRONMENT: "staging"
  ...
  - RELEASE: "(hidden)"
  ...
  - dist/index.js: "(hidden)"
Total Upload: 4.36 KiB / gzip: 1.05 KiB
```

Instead, you need to do `wrangler deploy dist/index.js --no-bundle --env ${env} --var RELEASE:${release}`
I'd expect the behaviour to be providing another `--var` if I wanted another (same as we do in wrangler pages dev)

**Comment by penalosa** [comment]
Unfortunately this is actually expected behaviour, and is a consequence of how [`yargs` parses arrays](https://github.com/yargs/yargs/blob/main/docs/api.md#array).

`wrangler deploy --no-bundle --env ${env} --var RELEASE:${release} dist/index.js` is parsed as:

```json
{
  "no-bundle": true,
  "env": ${env},
  "var": ["RELEASE:${release}", "dist/index.js"]
}
```

To end the array, you have to input `--`:

`wrangler deploy --no-bundle --env ${env} --var RELEASE:${release} -- dist/index.js`
