### ISSUE TITLE
🐛 BUG:parse error/incomplete input in D1

### ISSUE THREAD

**Issue by luxint** [cloudflare/workers-sdk#4326]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

wrangler 3.15.0

### What version of Node are you using?

v16.18.1

### What operating system are you using?

Linux

### Describe the Bug

The following trigger definition throws an error: incomplete input, works fine in sqlite
`CREATE TRIGGER my_table_after_insert_trigger 
  AFTER INSERT ON my_table
  BEGIN
    SELECT CASE WHEN NOT EXISTS(
      SELECT 1 FROM pragma_table_list(new."table")
    )
    THEN RAISE (ABORT , 'Exception, table does not exist') END ;
  END
;`
I found a workaround by enclosing the case statement with parentheses:
`CREATE TRIGGER my_table_after_insert_trigger 
  AFTER INSERT ON my_table
  BEGIN
    SELECT (CASE WHEN NOT EXISTS(
      SELECT 1 FROM pragma_table_list(new."table")
    )
    THEN RAISE (ABORT , 'Exception, table does not exist') END) ;
  END
;`

**Comment by nora-soderlund** [comment]
Adding a bit more info since this came up in the Discount guild:

I _believe_ that the issue arises from the compound statements only being started on `BEGIN` in the splitter:
https://github.com/cloudflare/workers-sdk/blob/4a735c46fdf5752f141e0e646624f44ad6301ced/packages/wrangler/src/d1/splitter.ts#L86

It might be easily solvable by changing this line to:
https://github.com/cloudflare/workers-sdk/blob/4a735c46fdf5752f141e0e646624f44ad6301ced/packages/wrangler/src/d1/splitter.ts#L156
```ts
return /\sBEGIN|CASE\s$/.test(str);
```
https://www.sqlite.org/lang_expr.html
