### ISSUE TITLE
🐛 BUG: Detect request to /favicon.ico and return 404 for Workers with no fetch handler

### ISSUE THREAD

**Issue by admah** [cloudflare/workers-sdk#4653]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.1

### What operating system are you using?

Mac

### Describe the Bug

When developing scheduled Workers, users see the following error in their console: "Error: Handler does not export a fetch() function". This is confusing, because scheduled Workers do not need a fetch handler.

The reason for this is that the browser automatically requests `favicon.ico` and can't find it resulting in Wrangler (Miniflare) throwing a 500 error. 

Instead, we should detect that it is a scheduled Worker, and return with a 404 for the missing favicon.

![Screenshot 2023-12-21 at 12 03 06 PM](https://github.com/cloudflare/workers-sdk/assets/2184114/4c643f2d-b553-4635-9d43-337d9173297f)

Related to #4560 

### Please provide any relevant error logs

`[wrangler:inf] GET /__scheduled 200 OK`
`[wrangler:err] Error: Handler does not export a fetch() function.
    at __facade_modules_fetch__`
`[wrangler:inf] GET /favicon.ico 500 Internal Server Error`

**Comment by OrlandoBricenoB** [comment]
Any advance with this? How can I build cron triggers for Workers?

**Comment by OrlandoBricenoB** [comment]
It seems that the code works when called by the trigger, but this error happens when we open the worker link without calling it to tell it that we want to fake a schedule trigger.

I'll quote the documentation: "Test Cron Triggers using Wrangler by passing in the --test-scheduled flag to [wrangler dev](https://developers.cloudflare.com/workers/wrangler/commands/#dev). This will expose a /__scheduled route which can be used to test using a HTTP request. To simulate different cron patterns, a cron query parameter can be passed in."
[Cron Triggers](https://developers.cloudflare.com/workers/configuration/cron-triggers/)
