### ISSUE TITLE
🐛 BUG: Logs with `at ` get truncated to `at [object Object]`

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workers-sdk#4668]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.1

### What version of Node are you using?

20.10.0

### What operating system are you using?

Windows 11

### Describe the Bug

With the following code:
```typescript
export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		console.log('some normal text to log')
		console.log('text with at the in the middle')
		return new Response('Hello World!');
	},
};
```
Running `npx wrangler dev` and then hitting the worker, results in:
```
[wrangler:inf] GET / 200 OK (14ms)
some normal text to log
text with at [object Object]
```

On further debug, it seems that `at` followed by a space, gets truncated to `at [object Object]` in all console logs. I suspect this line in `miniflare` is catching it:

https://github.com/cloudflare/workers-sdk/blob/main/packages/miniflare/src/plugins/core/errors/callsite.ts#L40

Originally reported on the forum: https://community.cloudflare.com/t/wrangler-dev-fails-to-properly-log-at-the/596263?u=cherryjimbo

**Comment by matthewjosephtaylor** [comment]
WOW I just spent like hours sanity checking and debugging and was about to file a similar report when I discovered this one. 

I tracked it down to 'that' but since 'at' is part of 'that', 'at' is prolly what the real problem is.

I'm on wrangler 3.22.3 on OSX

One of those 'makes you want to rethink life' kind of bugs. I'm going to be _quite_ curious as to what the cause and fix is.
