### ISSUE TITLE
🐛 BUG: Disabling minification doesn't seem to work

### ISSUE THREAD

**Issue by PANstudio** [cloudflare/workers-sdk#4756]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.3

### What version of Node are you using?

21.4.0

### What operating system are you using?

Windows

### Describe the Bug

[This Discord discussion](https://discord.com/channels/595317990191398933/1192896927684100136) suggests there is a `minify` option that can be set to `false` to disable Wrangler from minifying files in local development. However, this does not seem to be [documented](https://developers.cloudflare.com/workers/wrangler/configuration/#use-runtime-apis-directly0 and anyway doesn't seem to work.

Set up as follows:

*`package.json` command* (note local TOML file)

```
  "scripts": {
    ...
    "dev": "wrangler dev --config \"dev.toml\" --remote --port 1933",
    ...
}
```

*`dev.toml`*

```
name = "back"
main = "src/index.js"
compatibility_date = "2023-11-21"
node_compat = true
minify = false

[[hyperdrive]]
binding = "dev-db"
id = "*************"
localConnectionString = "postgres://**********************"
```

The result is that Wrangler continues to reference minified files when reporting errors, as per attached.
![image](https://github.com/cloudflare/workers-sdk/assets/4048196/e88608a2-e96c-4602-862a-4ae20dc28b75)

**Comment by penalosa** [comment]
While turning minification off does disable minification, the reason those stack traces don't correspond to lines in your source is because of [Wrangler's bundling](https://developers.cloudflare.com/workers/wrangler/bundling/) (in this case, probably to support npm packages you're including in your worker).

In your case, it looks like the problem is that `Router` is not defined. If you run Wrangler in local mode (i.e. `wrangler dev` without the `--remote` flag), Wrangler should be able to source-map the stack trace and show you where in your codebase you're referencing `Router`. In the future we may be able to source-map the stack traces in Worker uploads, but we don't have a timeline for that yet (cc @zebp)
