### ISSUE TITLE
🐛 BUG: TypeError in Cloudinary SDK: Issue with 'split' Property Access

### ISSUE THREAD

**Issue by watsuyo** [cloudflare/workers-sdk#4758]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.22.5

### What version of Node are you using?

20.10.0

### What operating system are you using?

Mac

### Describe the Bug

While utilizing the Cloudinary SDK, I encountered an unexpected error. The issue arises when making a request to the Cloudflare API for a specific worker script. The error message indicates a TypeError, specifically mentioning that the 'split' property cannot be read as it's undefined. This behavior was unexpected and seems to be a bug within the SDK or the integration with the Cloudflare API.

Error Message:

```javascript
[ERROR] A request to the Cloudflare API (/accounts/...) failed.
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
at null.<anonymous>
```

**Comment by penalosa** [comment]
Cloudflare doesn't maintain the Cloudinary SDK, and so this is probably best raised with the Cloudinary team (I think the relvant repo is https://github.com/cloudinary/cloudinary_npm?). I'm going to close this for now, but feel free to open a new issue if the underlying problem turns out to be on the Cloudflare end.
