### ISSUE TITLE
🐛 BUG: wasm error when using engineType = wasm into prisma

### ISSUE THREAD

**Issue by vcctm** [cloudflare/workers-sdk#4831]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.24.0

### What operating system are you using?

Mac

### Describe the Bug

So basically I'm following this [PRISMA + Cloudflare WORKER + Neon](https://prismaio.notion.site/Prisma-Cloudflare-Workers-and-Pages-107091db465f4ae08606dbf3070a0821?pvs=25#a63001e325de4738919b856973ba031c), to have on the edge runtime environment connection between prisma + neon into an cloudflare worker.

I'm following exactly this config but when running yarn dev (wrangler dev), I'm getting this issue: 

```
> node worker.build.js

✘ [ERROR] No loader is configured for ".wasm" files: ../../packages/content/node_modules/.prisma/client/query-engine.wasm

    ../../packages/content/node_modules/.prisma/client/edge.js:259:29:
      259 │         return (await import(`./query-engine.wasm`)).default
          ╵                              ~~~~~~~~~~~~~~~~~~~~~
```

I don't know what is related.

**Comment by penalosa** [comment]
We don't maintain that guide, so unfortunately we can't provide specific support with the setup. However, the error message you're getting is quite strange, since Wrangler should[ recognise `.wasm` files by default.](https://developers.cloudflare.com/workers/wrangler/bundling/#files-which-will-not-be-bundled) Would you be able to put together a reproduction repo?

**Comment by petebacondarwin** [comment]
Closing as there has been no response from the OP for a while and there is nothing actionable for us here.
