### ISSUE TITLE
🐛 BUG: Only one instance of Wrangler can be started

### ISSUE THREAD

**Issue by penalosa** [cloudflare/workers-sdk#4912]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

main

### What version of Node are you using?

18

### What operating system and version are you using?

macOS

### Observed behavior

Checkout & build Wrangler locally, and then run `npx wrangler dev` in `workers-sdk/fixtures/service-bindings-app/a` and then in `workers-sdk/fixtures/service-bindings-app/b`. The second command will fail with `Address already in use (127.0.0.1:9229)`

### Expected behavior

Multiple instances of Wrangler to be startable without error.

This first started regressing in https://github.com/cloudflare/workers-sdk/pull/4830, and hasn't yet been published in a Wrangler release.

### Please provide a link to a minimal reproduction

N/A

### Please provide any relevant error logs

N/A

**Comment by petebacondarwin** [comment]
This is not reproducible in node 16. I think it is a reoccurence of the old node 18 switching to IPV6 by default problem.

**Comment by petebacondarwin** [comment]
OK so looking into this I think the problem is this line where we use `localhost` for the host in the `getPort()` call:

https://github.com/cloudflare/workers-sdk/blob/48f9085981f0a4923d3ccc32596520107c4e4df8/packages/wrangler/src/dev.tsx#L715

I believe that what is happening here is that `localhost` gets resolve to both `127.0.0.1` and `::1`.
The first call to this (by Worker a) checks `localhost:9229` and is told it is free (because `127.0.0.1:9229` is free. So it uses that port and starts listening on `127.0.0.1:9229`.
The second call to this (by Worker b) checks `localhost:9229` and is told it is free (because `[::1]:9229` is free). So it uses that port and tries to start listening on `127.0.0.1:9229`which of course fails because that is already in use by Worker a.

If you change the line above to use 127.0.0.1 as the host explicitly then the second call (Worker b) gets a completely new port and that seems to solve the problem.

I think this does not fail in node 16 because it does not have support for IPV6 so calling `getPort()` with `localhost` only ever checks 127.0.0.1.

cc @Lekensteyn

**Comment by petebacondarwin** [comment]
An alternative solution is to ask workerd to listen on `localhost` explicitly, rather than leaving it undefined, which means that workerd is able to pick the other IP address, here:

https://github.com/cloudflare/workers-sdk/blob/884e41881687c34957bf22f97fb12a127707aef9/packages/wrangler/src/api/startDevWorker/ProxyController.ts#L127

But I am worried that we then have two different servers listening on `localhost:9229` and it is not clear how to distinguish between them. So I think the explicit use of IPv4 `127.0.0.1` across all these internal servers is the best approach.

**Comment by penalosa** [comment]
Fixed in https://github.com/cloudflare/workers-sdk/pull/4907
