### ISSUE TITLE
🐛 BUG: npm create cloudflare@latest --template <repo> still asks "What type of application?" prompt

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workers-sdk#4965]
refs https://github.com/cloudflare/cloudflare-docs/pull/12684 and https://github.com/cloudflare/workers-sdk/pull/4754

### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.11.3

### What version of Node are you using?

20

### What operating system and version are you using?

Mac

### To reproduce:

```
➜  npm create cloudflare@latest --template https://github.com/cloudflare/wildebeest

using create-cloudflare version 2.11.3

╭ Create an application with Cloudflare Step 1 of 3
│ 
├ In which directory do you want to create your application?
│ dir ./https://github.com/cloudflare/wildebeest
│
╰ What type of application do you want to create?
  ● "Hello World" Worker
  ○ "Hello World" Durable Object
  ○ Website or web app
```

Seems like `--template` is ignored and the template is being treated as the positional directory argument. Which doesn't make sense to me if directory is an optional field?

But then if I try to add a directory to the command:

```
> mkdir test
> npm create cloudflare@latest test --template 'https://github.com/cloudflare/wildebeest'
Too many positional arguments provided
```

Referring back to the docs in https://github.com/cloudflare/cloudflare-docs/pull/12684/files#diff-2b2a14b95369fcdd2c0124db5d889e755f66ec047cc682281717849e3a29602dR100 — wasn't clear to me how I should go about figuring this out.

I realized eventually that `--` is required, but only by looking at this:

```
npm create cloudflare@latest [--] [<DIRECTORY>] [OPTIONS] [-- <NESTED ARGS...>]
```

ex:
```
npm create cloudflare@latest -- test --template cloudflare/wildebeest
```

(seems like actual examples could go a long way here, show you that `--` is required)

I'm not sure why `--` is required at all though. Is this a common pattern? Where does it come from? For context on where I'm coming from, my go-to reference for CLI design is https://clig.dev/.

Is there an explicit reason why it's not possible or not a good idea for `npm create cloudflare@latest --template <repo>` to just work? I'd have expected it to work, and don't think I'm alone on that.

@admah @jculvey — curious for your thoughts — something I'm missing?

**Comment by jculvey** [comment]
This is an unfortunate feature of `npm create` 😓. 

Any of the following commands would have worked like you were expecting:

- `pnpm create cloudflare@latest --template https://github.com/cloudflare/wildebeest`
- `bun create cloudflare@latest --template https://github.com/cloudflare/wildebeest`
- `yarn create cloudflare --template https://github.com/cloudflare/wildebeest`
- `npx create-cloudflare@latest --template https://github.com/cloudflare/wildebeest`

`npm exec` (and thus `npm create` aka `npm init`), in contrast with all other package managers and npm subcommands, requires `--` to indicate that npm should stop parsing command line arguments and send the remaining arg string to the executed command. More info can be found in the docs [here](https://docs.npmjs.com/cli/v10/commands/npm-exec#npx-vs-npm-exec).

It's annoying because there's nothing we can really do about it in c3, since this behavior is completely controlled by npm. By the time c3 gets the argument string from `npm create cloudflare@latest --template foo`, `npm` has already decided that `--template` was a switch it was supposed to parse and handle (which it did by doing absolutely nothing), and passes c3 an args string with the template url `foo` which it thinks is a positional argument.

This is something we're going to need to solve by clarifying in the docs. I think you raise a good point that while the existing docs have a detailed explanation of what each argument does, they could benefit from also having a working example of a c3 invocation with that flag via `npm create`.

**Comment by irvinebroque** [comment]
Thanks @jculvey! This makes sense to me now.

We def need to be super loud about this in docs in this case. @admah 

Wonder if we should point people to `npx create-cloudflare@latest` since it gets around this?

**Comment by admah** [comment]
> Wonder if we should point people to npx create-cloudflare@latest since it gets around this?

I think so. This definitely makes it simpler. I'll get a docs PR up.
