### ISSUE TITLE
🚀 Feature Request: add support for send_metric = false wrangler.toml configuration for wrangler cli

### ISSUE THREAD

**Issue by pcostanz** [cloudflare/workers-sdk#5117]
### Describe the solution

The "Would you like to help improve Wrangler by sending usage metrics to Cloudflare?" prompt blocks CLI start commands, in cases where we're trying to get temporary projects running (demos, interviews, etc) and don't want to require people to initialize wrangler with a CF account.

It would be nice to be able to `wrangler pages dev --send-metric=false` since pages cannot make use of the wrangler.toml `send_metric = false` setting.

In our case the `wrangler dev` command fails because of the prompt, but the vite server starts so it is hard to decipher what's broken / how to fix it for someone without prior knowledge of wrangler (which isn't important for this use case).

<img width="370" alt="Screenshot 2024-02-28 at 1 46 51 PM" src="https://github.com/cloudflare/workers-sdk/assets/2976552/5fca6ef1-90b0-44d9-a494-bcf32e0c77bc">

**Comment by CarmenPopoviciu** [comment]
hi @pcostanz. Thank you for reporting this issue.

Now that Pages supports `wrangler.toml`, incl. `send_metrics`, it doesn't look like this issue is still relevant. Looking at `wrangler dev`, which dows not suppor `send_metrics` via a cli arg, but only via `wrangler.toml`, I feel like both `wrangler dev` and `wrangler pages dev` are on par as far as `send_metrics` field is concerned.

Closing, but if you strongly disagree with my sentiment, pls re-open and share your thoughts <3
