### ISSUE TITLE
🚀 Feature Request: Please add Pages Functions support for Direct Upload!

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/workers-sdk#5216]
### Describe the solution

Hello,

I have a pretty good mix of SFW and NSFW websites,
therefore _I am using Direct Upload for everything for a nice unified architecture_,
since **NSFW content obviously cannot be uploaded to GitHub and such.**

This unfortunately means I cannot take advantage of [Pages Functions](https://developers.cloudflare.com/pages/functions/),
since ["Direct Upload is currently not supported with Functions"](https://developers.cloudflare.com/pages/functions/get-started/).

_**This is a devastating limitation!**_

I think _Direct Upload should be considered as a first-class citizen_,
so **please add Pages Functions support for Direct Upload!**

**Comment by dario-piotrowicz** [comment]
Hi @Hexstream 👋 

Direct Upload _does_ support Pages functions, our docs are incorrect, as you can see here: https://github.com/cloudflare/cloudflare-docs/pull/8389, the warning you linked was supposed to state:

> Using [Direct Uploads](/pages/platform/direct-upload/) __from the Cloudflare dashboard__ is currently **not supported** with Functions.

but the "from the Cloudflare dashboard" bit has been incorrectly removed, I'll open a PR in our docs repo to amend this mistake

So please try to perform direct uploads via `wrangler pages deploy` and let me know if that works for you 👍 

(Unless this issue is indeed in regards to direct uploads __from the Cloudflare dashboard__?)

**Comment by Hexstream** [comment]
Oh wow, _**AWESOME!!!_**

Yes, I only care about Direct Upload from wrangler.

I'll try Pages Functions soon, then!
Thank you!

**Comment by dario-piotrowicz** [comment]
No problem @Hexstream 🙂 

Sorry for the confusion 🙇 , I've already opened the PR for amending our docs: https://github.com/cloudflare/cloudflare-docs/pull/13340

(please feel free to comment there if you find the wording not clear enough)

I'm closing this issue as I think we're all good then, hopefully that's fine by you 🙂, if you still have issues with direct uploads please feel free to open a new issue

**Comment by Hexstream** [comment]
Perfect, thank you!
