### ISSUE TITLE
🐛 BUG: Need a better error for dev-ing Python modules when missing the `python_workers` compatibility flag

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#5479]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.43.0

### What operating system and version are you using?

macOS

### Describe the Bug

If you're missing the `compatibility_flags = ["python_workers"]` in your `wrangler.toml`, you just get an opaque

```
✘ [ERROR] service core:user:worker: Uncaught Error: internal error


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

when trying to `wrangler dev`.

This should be improved to instead be a useful error message prompting the user to add that flag to their config file.

**Comment by Al3676** [comment]
Good good all paranys

**Comment by dom96** [comment]
It looks like Wrangler is not showing the full output from workerd. When I run workerd on a Python Worker without this compat flag I get:

```
workerd/jsg/util.c++:291: error: e = workerd/server/workerd-api.c++:399: failed: expected featureFlags.getPythonWorkers(); The python_workers compatibility flag is required to use Python.
stack: [...long stack trace...]
service main: Uncaught Error: internal error
```

This possibly needs to be fixed in Wrangler. @cloudflare/wrangler thoughts?

**Comment by penalosa** [comment]
I suspect this is being hidden because we hide some error logs that come from workerd which aren't useful to the user. Potentially we're being over zealous here, and hiding too much.

However, I wonder if it'd be a nicer experience to throw an error here much earlier in the process—when we detect that a user has a .py file without the compatibility flag. I think we could do this in `readConfig()`, where we currently apply the no bundling rules for python workers.
