### ISSUE TITLE
🐛 BUG: Need a better error for when omitting a default export

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/workers-sdk#5487]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.43.0

### What version of Node are you using?

20.12.0

### What operating system and version are you using?

macOS

### Describe the Bug

With named entrypoints, it's going to be quite easy for people to forget to `export default {}`. Without it, Wrangler will just bundle as CJS, expecting SW syntax. This means you'll likely get an error like:

```
✘ [ERROR] service core:user:my-service: Uncaught Error: Dynamic require of "cloudflare:workers" is not supported
```

It's not clear to users that they need to add a `export default { fetch() { return new Response("ok") } }` to their script given this.

**Comment by penalosa** [comment]
See https://github.com/cloudflare/workers-sdk/issues/5663#issuecomment-2216980515 for some more context

**Comment by JustFly1984** [comment]
I was burned by omitting fetch method on RPC worker class extended from WorkerEntrypoint. An error is "The uploaded script has no registered event handlers".
wrangler.toml "format" setting is not supported anymore, class is exported with export default.
I'm using the typescript, and while addding fetch method, it complains that I have to use overrides keyword, cos fetch is already defined on parent WorkerEntrypoint class.
Is it intentional or a bug?

**Comment by penalosa** [comment]
This was addressed by https://github.com/cloudflare/workers-sdk/pull/6872
