### ISSUE TITLE
🐛 BUG: Scheduled Handler not found in Local Dev

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/workers-sdk#5548]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.48.0

### What version of Node are you using?

21.7.2

### What operating system and version are you using?

macOS Sonoma 14.4.1

### Observed behavior
When developing a Worker with a scheduled handler, invoking the handler via `http://localhost:8787/cdn-cgi/mf/scheduled` throws the following error:
> ✘ [ERROR] Received a ScheduledEvent but we lack a handler for ScheduledEvents (a.k.a. Cron Triggers). Did you remember to export a scheduled() function?

### Expected behavior
`scheduled` handler should be detected and executed.

### Steps to reproduce
Please provide the following:
- Worker Code
```js
export default {
	scheduled() {
		console.log("Hey!");
	}
}
```
- `wrangler.json`:
```json
{
	"name": "cron-test",
	"main": "index.js",
	"compatibility_date": "2024-04-07",
	"triggers": {
		"crons": ["0 0 * * * * *"]
	}
}
```
- Command to start:
```sh
wrangler dev -j
```
- `curl` command:
```sh
$ curl http://localhost:8787/cdn-cgi/mf/scheduled
exception%
```

### Please provide any relevant error logs

```
$ wrangler dev -j

 ⛅️ wrangler 3.48.0
-------------------
⎔ Starting local server...
▲ [WARNING] Miniflare 3 does not support CRON triggers yet, ignoring...


[wrangler:inf] Ready on http://localhost:8787
✘ [ERROR] Received a ScheduledEvent but we lack a handler for ScheduledEvents (a.k.a. Cron Triggers). Did you remember to export a scheduled() function?
```

**Comment by penalosa** [comment]
The way to test scheduled handlers with Wrangler in local dev is to use the `--test-scheduled` flag and `/__scheduled` (see https://developers.cloudflare.com/workers/runtime-apis/handlers/scheduled/ for docs). I'll close this issue for now—feel free to open a new one if that doesn't work for your use case.

`/cdn-cgi/mf/scheduled` will work when using Miniflare directly, but doesn't work when using Wrangler because of the dev server architecture (we run two Miniflare instances, only one of which has the user worker, and the non-user worker one handles the `/cdn-cgi/mf/scheduled` endpoint.)
