### ISSUE TITLE
🚀 Feature Request: Add support for Source Maps > 5MB

### ISSUE THREAD

**Issue by hrueger** [cloudflare/workers-sdk#5627]
### Describe the solution

Hi,
I'd really appreciate if source maps > 5 MB could be used, too. My application is not too bug, but the source map is about 8 MB. Probably due to dependencies (prisma for example).
Thanks in advance!

Error:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts/redacted-production) failed.

  sourcemap worker.js.map is too large, must not exceed 5MB [code: 10021]
```

**Comment by penalosa** [comment]
@hrueger Thanks for reporting this! We're investigating this internally, and are considering what size of sourcemap we want to support in the future. I've sent this issue to the relevant team for consideration, but since this is an API layer concern rather than a Wrangler one I'm going to close this issue for now.

**Comment by adamdehaven** [comment]
@penalosa I'm running up against the same issue now, even though the current limit appears to be `15MB`

Depending on the application (e.g. in my case Nuxt + Nitro) deployed to a worker, the size of the sourcemap can be `X MB` large. 

- Is there a technical reason for the sourcemap size limit? 
- Would it be possible to push the sourcemap files separately from the worker, and somehow attach?
- Any recommendations on "splitting up" the sourcemaps before uploading via wrangler?
