### ISSUE TITLE
🚀 Feature Request: deprecate `preview_id` config for KV and others

### ISSUE THREAD

**Issue by deadlypants1973** [cloudflare/workers-sdk#5639]
### Describe the solution

Filing this issue to reflect commentary made in https://github.com/cloudflare/cloudflare-docs/issues/13493.

We should deprecate preview in Wrangler and encourage/educate on the use of environments.

CC: @penalosa as collaborator on this issue

**Comment by penalosa** [comment]
cc @irvinebroque this is related to the `preview_id` fields that bindings have that are used when in remote mode dev

**Comment by petebacondarwin** [comment]
Since the `preview_id` is required when using `--remote` mode dev we can't really just deprecate it. Instead we should think about the long term strategy of replacing remote mode which would make removing this a moot point.
Closing as there is not much we can do about this right now, given that the docs have been updated to help guide the user.
