### ISSUE TITLE
🐛 BUG: wrangler d1 execute cannot create tables with reserved words in double quotes

### ISSUE THREAD

**Issue by joshthoward** [cloudflare/workers-sdk#5876]
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.57.0 Wrangler

### What version of Node are you using?

v20.6.1

### What operating system and version are you using?

Mac Sonoma

### Observed behavior
`d1 execute <db_name>  --command="CREATE TABLE myTable ("group" TEXT);"` throws the error `✘ [ERROR] near "group": syntax error at offset 22`

### Expected behavior
This is valid SQLite syntax and shouldn't throw.

### Steps to reproduce
N/A

**Comment by penalosa** [comment]
This is probably because of your shell's quoting behaviour. If the exact command you're running is `wrangler d1 execute <db_name>  --command="CREATE TABLE myTable ("group" TEXT);"` then Wrangler will see the string `CREATE TABLE myTable (group TEXT);` (without the quotes).

To make this work as expected, you'll need to escape the inner quotes: `wrangler d1 execute <db_name>  --command="CREATE TABLE myTable (\"group\" TEXT);"`.
