### ISSUE TITLE
🚀 Feature Request: Implement "wrangler check-update" to check current version

### ISSUE THREAD

**Issue by arisris** [cloudflare/workers-sdk#6190]
### Describe the solution

- **Summary**: This command will check the current version of "wrangler" instead of executing it directly in the **printWranglerBanner()** function
- **Motivation**: This command will increase the speed of executing subcommands rather than checking the latest version directly every time. This will reduce internet data load for local users
- **Alternatives Considered**: If it is not possible to add this command. Can we cache the updateCheck() version for some time? For example once a day?

I think features like this are very crucial. However, if we check the latest version every time we run a command, for example "wrangler whoami", it will feel very slow, especially for users who have slow/limited internet data.

https://github.com/cloudflare/workers-sdk/blob/8890c5bbffbb3019486a77c67c72576b71b0adb0/packages/wrangler/src/update-check.ts#L8

https://github.com/cloudflare/workers-sdk/blob/8890c5bbffbb3019486a77c67c72576b71b0adb0/packages/wrangler/src/update-check.ts#L43

Thankyou

**Comment by CarmenPopoviciu** [comment]
hi @arisris,

thank you for raising this feature request with us!

wrangler's `printWranglerBanner()` uses [update-check](https://www.npmjs.com/package/update-check) under the hood, which already has the kind of caching mechanism you are referring to, in place:

```
update = await checkForUpdate(pkg, {
        interval: 3600000,  // For how long to cache latest version (default: 1 day)
        distTag: 'canary'   // A npm distribution tag for comparison (default: 'latest')
    });
```

As you can see from their docs 👆, by default, the latest version is cached for 1 day. This is the default [we are using](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/update-check.ts#L46-L49) as well. I think this is a fair balance in terms command performance vs version accuracy.

As for supporting a separate `check-update` command, given all of the above I don't think there is a real need for that. I'm going to go ahead and close this, since the alternative solution you requested is already in place.

thank you again for helping us make wrangler better <3

**Comment by arisris** [comment]
Hi @CarmenPopoviciu Tanks for your response.

Yes, I see befoe. But the option to disable it seems worth considering. considering that checking the current version will download a json file from the registry "https://registry.npmjs.org/wrangler" around >=18mb which will probably get bigger over time. and this will waste data in vain just to check the latest version. It doesn't matter if our internet is fast, but if it's slow? this will be very noticeable.

Another alternative might be to create an http api that only downloads the string version rather than downloading a large json file directly from the registry?
