### ISSUE TITLE
feat: implement bundle splitting

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workers-sdk#637]
We currently bundle all the javascript into one file, which is fine for most usecases. For heavier workers, a common usecase is to use lazy imports to only execute code that's required (via routing or some other form of dispatch). The internals of our module system allow for chunks of js to be loaded. We should wire up esbuild's bundle splitting to match this system. 

Not a blocker for 2.0, not high pri. Might take a small refactor.

**Comment by threepointone** [comment]
I quickly tried this, and looks Workers doesn't support lazy imports yet, which would make this implementation hard. We should fix that internally first.

**Comment by petebacondarwin** [comment]
Dynamic imports in Workers is being implemented soon.

But I am not convinced that this will provide much benefit to the majority of Workers. There is already quite a hard limit on the size of a Worker bundle (including all dynamically loaded files) and delaying the loading until runtime could actually reduce the performance of the Worker - the initial JS for a Worker is parsed before a request is handled, so that time is not charged to the user; once a Worker instance has been spun up, the JS does not need to be parsed again. Any dynamically loaded JS would need to be parsed as part of the running time of the Worker handling the request, for which it would be charged.

I think that service-bindings, where Workers can "call though" to other Workers via a high-speed connection are better placed to support the needs of a larger application. One thing that Wrangler should look into, perhaps, is splitting code between Workers and automatically configuring them up as service bindings?

**Comment by threepointone** [comment]
Yeah probably. One idea I had there was to support something like this-
```js
import Worker from "worker:path/to/file.js";
//... 
Worker.fetch(request, env)
```

(Similar to what we're thinking about for assets). 

We should probably file a separate issue for this.

**Comment by penalosa** [comment]
Closing this for now, since `--no-bundle` fits this use case. There will be feature enhancements there, but they should be tracked in a separate issue.
