### ISSUE TITLE
🚀 Feature Request: Workers AI please support the new qwen2.5 model

### ISSUE THREAD

**Issue by zhu327** [cloudflare/workers-sdk#6810]
### Describe the solution

The new qwen2.5 model has been released, and while the model size remains unchanged, its responses are more accurate. So I would like to ask if there are plans to update to qwen2.5?

**Comment by andyjessop** [comment]
Hey @zhu327 - we're working on the capability to "run any model", which is planned for the coming months. So rather than supporting a specific model, you will be able to "bring your own model". There's some information [here](https://blog.cloudflare.com/workers-ai-bigger-better-faster/), but the advice is to stay tuned for the moment.
