### ISSUE TITLE
Wrong template linked?

### ISSUE THREAD

**Issue by tsteckenborn** [cloudflare/workers-sdk#6847]
The documentation for workers deployment of remix, seems to link to this c3 template (see https://developers.cloudflare.com/workers/frameworks/framework-guides/remix/ and https://github.com/cloudflare/cloudflare-docs/issues/17148)

https://github.com/cloudflare/workers-sdk/blob/b3335b7da90b3d0c5b0c7d1848a546c55de1fce2/packages/create-cloudflare/templates-experimental/remix/c3.ts#L13-L21

Yet this is linking to the pages template of remix (or could someone explain why all commands are still wrangler pages dev)?

There seems to be another one for workers (https://github.com/remix-run/remix/tree/main/templates/cloudflare-workers) yet this is apparently not yet merged with static assets and the like (see pr https://github.com/remix-run/remix/pull/10034).

Somehow a quite confusing situation right now?

**Comment by tanushree-sharma** [comment]
Thanks for filing this issue.

Workers Assets is in beta, including our framework support. You’re seeing this because the Workers C3 templates are based off of the Pages templates. The migration is often just a few lines of code and C3 does it for you:

- Updates the wrangler.toml file to use Workers Assets 
- Adds an .assetsignore file to the static directory so that we avoid uploading any metafiles as static assets
- Updates package.json's deploy command to use wrangler deploy rather than wrangler pages deploy. 

We're planning to upstream these changes to the various framework adaptors and templates.
