### ISSUE TITLE
🚀 Feature Request: Support Bun

### ISSUE THREAD

**Issue by 7heMech** [cloudflare/workers-sdk#7449]
### Describe the solution

When I try to make a new project with Bun on Windows I get this error message:
```js
C:\Users\Mech\Documents\CODE>wrangler init

 ⛅️ wrangler 3.92.0
-------------------


X [ERROR] Unable to find a package manager. Supported managers are: npm, yarn, and pnpm.
```
Can Bun support be added?

**Comment by penalosa** [comment]
We don't intend to add support for bun in `wrangler init`, but bun is supported by `create-cloudflare`. I'm not that familiar with Bun, but I imagine you'd run it with `bun create cloudflare`.

That said, Wrangler does not currently support bun, and we don't intend to add support. The majority of the complexity of Wrangler comes from the interaction between Node and `workerd` (the open source Cloudflare Workers runtime), and adding a third runtime into the mix there would add a lot of additional complexity for not much clear benefit. To give just one example, the Miniflare Queues simulator relies on the v8 serialisation behaviour exposed by Node, which I imagine wouldn't work in Bun because it's based on JavaScript Core.

**Comment by tranzium** [comment]
Just realized this is a thing when trying to convert from node to bun.

_If I was not in Windows, I would symbolically link node to bun so fast._

Sadly, adding a node.exe to my /bin folder will be the solution... for now.

**Comment by 7heMech** [comment]
> Just realized this is a thing when trying to convert from node to bun.
> 
> _If I was not in Windows, I would symbolically link node to bun so fast._
> 
> Sadly, adding a node.exe to my /bin folder will be the solution... for now.

Yeah, it's so unfortunate.

**Comment by mountainash** [comment]
For people coming here looking for Wrangler to support Bun... please follow a reversed request for [Bun to support Wrangler](https://github.com/oven-sh/bun/issues/10464)
